name: Convert Python to Jupyter Notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  convert-to-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbformat
    
    - name: Run JINC conversion
      run: |
        # Get the list of changed files
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)
        
        for py_file in $CHANGED_FILES; do
          # Skip jinc.py
          if [[ "$py_file" == *"jinc.py"* ]]; then
            echo "Skipping JINC program: $py_file"
            continue
          fi
          
          ipynb_file="${py_file%.py}.ipynb"
          if [ ! -f "$ipynb_file" ] || [ "$py_file" -nt "$ipynb_file" ]; then
            echo "Converting $py_file to $ipynb_file"
            python jinc.py "$py_file" -o "$ipynb_file"
          else
            echo "Notebook is up to date for $py_file, skipping"
          fi
        done
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        if [[ -n $(git status -s) ]]; then
          git add -A
          CHANGED_NOTEBOOKS=$(git diff --cached --name-only | grep '\.ipynb$' | xargs)
          git commit -m "Update Jupyter notebooks: $CHANGED_NOTEBOOKS"
          git push
        else
          echo "No changes to commit"
        fi